### PR TITLE
0.5 is no longer current

### PR DESCRIPTION
**Pull request by PallHaraldsson**

### CODE REVIEW

**Comment by sunoru** [comment]
Yes, thanks!

**Comment by PallHaraldsson** [comment]
I had an issue about changing the default for 1.0 but it was too late.

I believe the RNG was unchanged in 0.6; and then at least from 0.6 to 0.7/1.0.

**Comment by sunoru** [comment]
Yes.. And I was also too busy to follow the discussion about changing the default RNG.

**Comment by PallHaraldsson** [comment]
That was fast... or me slow writing. At least 0.5 is no longer current. As I said, I assume the RNG hasn't changed.

**Comment by sunoru** [comment]
You are right. It hasn't been changed (still the DSFMT). I forgot to update the docs.

**Comment by PallHaraldsson** [comment]
Should it say "up to and including current 1.0" or even say 1.0.2 that I now see is out?

**Comment by sunoru** [comment]
Maybe it's better. I think the current expression is OK.

**Comment by PallHaraldsson** [comment]
"The **Mersenne Twister**[^1] is so far the most widely used PRNG."

Did you mean to say "*by* far"? In case I make the change about, would this one be also ok?

**Comment by sunoru** [comment]
What do you mean by "by far"? I'm sorry for not understanding English well..

**Comment by PallHaraldsson** [comment]
"so far" = up to now.
"by far" = way more [popular], not just "the most widely used PRNG". "so far" could mean, not much more popluar) and possibly not for much longer. happens to be most used

I think you're also not wring this for Julia software, where MT happens to be most used, but I guess youðre trying to change that. :)

**Comment by sunoru** [comment]
Thank you :) Actually I wanted to say "up to now" in that sentence, for I'm hoping there can be something such as `xoroshiro` to be the new most used one.

**Pull request merged**
